use cigardb;

DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS ADDRESS;


CREATE TABLE ADDRESS(
	IDADDRESS INTEGER NOT NULL AUTO_INCREMENT,
	CITY VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(256),	
	PRIMARY KEY(IDADDRESS)
);

CREATE TABLE CUSTOMER(
   LOGIN VARCHAR(30) NOT NULL,
   PASSWORD VARCHAR(256) NOT NULL,
   NOM VARCHAR(100) NOT NULL,
   PRENOM VARCHAR(100) NOT NULL,
   IDADDRESS INTEGER NOT NULL,
   EMAIL VARCHAR(100) NOT NULL,
   Foreign Key (IDADDRESS) references ADDRESS(IDADDRESS),
   PRIMARY KEY(LOGIN)
);

CREATE TABLE ROLE(
   IDROLE  INTEGER NOT NULL AUTO_INCREMENT,
   ROLELABEL VARCHAR(256) NOT NULL,
   LOGIN VARCHAR(30) NOT NULL,
   PRIMARY KEY(IDROLE),
   Foreign Key (LOGIN) references CUSTOMER(LOGIN)
);

INSERT INTO ADDRESS(CITY,ADDRESS) VALUES('St Germain en laye','10 rue de tolbiac, 78000 St Germain');
INSERT INTO ADDRESS(CITY,ADDRESS) VALUES('Paris','Rue Mozart, 75016 Paris');

INSERT INTO CUSTOMER(LOGIN,PASSWORD,NOM,PRENOM,IDADDRESS,EMAIL) values ('Didier','Didier','Bonnet','Didier',1,'gzouli_karim@yahoo.fr');
INSERT INTO CUSTOMER(LOGIN,PASSWORD,NOM,PRENOM,IDADDRESS,EMAIL) values ('Karim','Karim','Gzouli','Karim',2,'gzouli_karim@yahoo.fr');
INSERT INTO ROLE(ROLELABEL,LOGIN) VALUES('customer','Didier');
INSERT INTO ROLE(ROLELABEL,LOGIN) VALUES('customer','Karim');