use cigardb;

DROP TABLE IF EXISTS CIGARORDERLINE;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CREDITCARD;

CREATE TABLE CREDITCARD(
    IDCREDITCARD INTEGER NOT NULL AUTO_INCREMENT,
    CREDITCARDTYPE VARCHAR(100) NOT NULL,
    CREDITCARDNUMBER VARCHAR(100) NOT NULL,
    EXPIRATIONDATE VARCHAR(8) NOT NULL,
    PRIMARY KEY(IDCREDITCARD)
);


CREATE TABLE ORDERS(
	IDORDER INTEGER NOT NULL AUTO_INCREMENT,
	TOTALAMOUNT double NOT NULL,
	LOGIN VARCHAR(30) NOT NULL,
	IDCREDITCARD INTEGER NOT NULL,
   
	Foreign Key (LOGIN) references CUSTOMER(LOGIN),
	Foreign Key (IDCREDITCARD) references CREDITCARD(IDCREDITCARD),
	PRIMARY KEY(IDORDER)
	
);

CREATE TABLE CIGARORDERLINE(
	IDCIGARORDERLINE INTEGER NOT NULL AUTO_INCREMENT,
	QUANTITY INTEGER NOT NULL,
	IDCIGAR INTEGER NOT NULL,
	IDORDER INTEGER NOT NULL,
	Foreign Key(IDORDER) references ORDERS(IDORDER),
    Foreign Key (IDCIGAR) references CIGAR(IDCIGAR),
	PRIMARY KEY(IDCIGARORDERLINE)
);



