
package test.bank.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.3-hudson-757-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BankServiceImplService", targetNamespace = "http://service.bank.test/", wsdlLocation = "http://localhost:8281/MerchantBank-1.0/BankServiceImplService?WSDL")
public class BankServiceImplService
    extends Service
{

    private final static URL BANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(test.bank.service.BankServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = test.bank.service.BankServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8281/MerchantBank-1.0/BankServiceImplService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8281/MerchantBank-1.0/BankServiceImplService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BANKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public BankServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankServiceImplService() {
        super(BANKSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.bank.test/", "BankServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns IBankService
     */
    @WebEndpoint(name = "BankServiceImplPort")
    public IBankService getBankServiceImplPort() {
        return super.getPort(new QName("http://service.bank.test/", "BankServiceImplPort"), IBankService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBankService
     */
    @WebEndpoint(name = "BankServiceImplPort")
    public IBankService getBankServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bank.test/", "BankServiceImplPort"), IBankService.class);
    }

}
